Fixes and clean up for TPC-H examples
Bodo-inc/Bodo-examples pull request #52
Opened 2022-04-17 00:35 UTC by ehsantn

Clean up like removing unnecessary code and fixed formatting.

2022-04-18 15:34 UTC, alifarhid requested changes
@ehsantn just some minor stylish comments. I guess black sometime broke into newlines which is not helping with readability.

2022-04-18 15:34 UTC, alifarhid commented on examples/tpch/generate_data_pq.py
> +    )  # * dbgen only produces one file for nation with SF1000 *
@ehsantn any reason each entry in this tuple is broken into new lines?

2022-04-18 15:34 UTC, alifarhid commented on examples/tpch/generate_data_pq.py
> +    tables["supplier"] = ("s", num_pieces_base // 100, load_supplier)
same as above, tuple entries in newlines.

2022-04-18 15:34 UTC, alifarhid commented on examples/tpch/generate_data_pq.py
> +    tables["supplier"] = ("s", num_pieces_base // 100, load_supplier)
perhaps you ran black on these files and due to the comma at the end of load_region, it broke the entries into newlines.

2022-04-18 15:34 UTC, alifarhid commented on examples/tpch/generate_data_pq.py
> +    ) = args
same here

2022-04-18 15:34 UTC, alifarhid commented on examples/tpch/generate_data_pq.py
same

2022-04-18 15:34 UTC, alifarhid commented on examples/tpch/generate_data_pq.py
> +    )
same

2022-04-18 15:34 UTC, alifarhid commented on examples/tpch/generate_data_pq.py
>          type=float,
same

2022-04-18 15:34 UTC, alifarhid commented on ml/README.md
> +watch your [htop](https://formulae.brew.sh/formula/htop) in terminal and enjoy your CPUs running at full capacity.
sometimes CPUs won't go beyond 70-80%, that's why we tried to avoid saying full capacity (100%).

2022-04-18 20:18 UTC, ehsantn commented on ml/README.md
> +watch your [htop](https://formulae.brew.sh/formula/htop) in terminal and enjoy your CPUs running at full capacity.
CPUs working is not the same as "maximum efficiency" so I'd be careful. I'll find a better word.

2022-04-18 20:22 UTC, ehsantn commented on examples/tpch/generate_data_pq.py
> +    )  # * dbgen only produces one file for nation with SF1000 *
`black` does this when the line is too long. I moved the comment above which fixed the issue.

2022-04-18 20:22 UTC, ehsantn commented on examples/tpch/generate_data_pq.py
> +    tables["supplier"] = ("s", num_pieces_base // 100, load_supplier)
comma doesn't matter for `black`. The line was too long so I move the comment.

2022-04-18 20:23 UTC, ehsantn commented on examples/tpch/generate_data_pq.py
> +    ) = args
`black` is trying to avoid long lines. This is worse than long lines?

2022-04-18 22:34 UTC, ehsantn commented on ml/README.md
> +all your CPU cores working hard on ML problems!
@alifarhid  Is this better?

2022-04-19 04:24 UTC, alifarhid commented on ml/README.md
> +all your CPU cores working hard on ML problems!
It's Ok @ehsantn . Just not sure why you added ML problems? On any data processing CPU cores are working hard.

2022-04-19 04:26 UTC, alifarhid approved these changes

2022-04-19 04:26 UTC, merged