Chicago Crimes Example
Bodo-inc/Bodo-examples pull request #56
Opened 2022-04-27 15:14 UTC by bodo-sai

2022-04-27 15:30 UTC, alifarhid requested changes
Please add the followings:
1. instruction on how to run locally on Docker. 
2. Test end to end on AWS EKS. There are problems there that needs to be fixed. Not sure what are the problems.

2022-05-08 02:54 UTC, sahil1105 commented on Kubernetes/README.md
> -### Step 1: Create a Kubernetes Cluster in EKS
Why remove this step? We could mark it as optional instead? Would be good as a reference for people with limited K8s experience.

2022-05-08 02:55 UTC, sahil1105 commented on Kubernetes/README.md
> +You can use this as the base image for your own docker image. For testing and validation purposes this image also includes the [Chicago Crimes example](docker/chicago_crimes.py), which is used in thi
I think we can include both examples. `pi.py` is easier for validation purposes.

2022-05-08 02:55 UTC, sahil1105 commented on Kubernetes/README.md
> +1. update `spec.slotsPerWorker` with the number of physical cores (_not_ vCPUs) on each node
```suggestion
1. Update `spec.slotsPerWorker` with the number of physical cores (_not_ vCPUs) on each node.
```

2022-05-08 02:55 UTC, sahil1105 commented on Kubernetes/README.md
> +2. set `spec.mpiReplicaSpecs.Worker.replicas` to the number of worker nodes in your cluster.
```suggestion
2. Set `spec.mpiReplicaSpecs.Worker.replicas` to the number of worker nodes in your cluster. 
```

2022-05-08 02:56 UTC, sahil1105 commented on Kubernetes/README.md
> +3. Build the image using the Dockerfile and replace the image at `spec.mpiReplicaSpecs.Launcher.template.spec.containers.image` and  `spec.mpiReplicaSpecs.Worker.template.spec.containers.image`.
I would also upload an image to our DockerHub, so people can test more easily.

2022-05-08 02:57 UTC, sahil1105 commented on Kubernetes/docker/pi.py
> -"""
I'd keep this as well.

2022-05-08 02:58 UTC, sahil1105 commented on Kubernetes/docker/Dockerfile
> +ENV PATH /root/miniconda3/bin/:${PATH}
Are we sure `root` works in all cases? MPI usually doesn't like to be run using the root user.

2022-05-08 03:00 UTC, sahil1105 commented on Kubernetes/docker/chicago_crimes.py
> +print("Determining the pattern on monthly basis\n")
Add this and everything below in a `main` function and then call using `if __name__ == '__main__'`?

2022-05-08 03:00 UTC, sahil1105 commented on Kubernetes/docker/chicago_crimes.py
> +print(f"Hello World from rank {bodo.get_rank()}. Total ranks={bodo.get_size()}")
Add this and everything below in a `main` function and then call using `if __name__ == '__main__'`?

2022-05-08 03:00 UTC, sahil1105 commented on Kubernetes/mpijob.yaml
> +apiVersion: kubeflow.org/v1
Revert?

2022-05-08 03:01 UTC, sahil1105 commented on Kubernetes/mpijob.yaml
> +            - image: <YOUR-DOCKER-IMAGE-HERE>
Same as above, I would upload one to our DockerHub to make testing easier.

2022-05-08 03:02 UTC, sahil1105 reviewed
Thanks @bodo-sai!
As discussed, we also need to get a better understanding of how we resource allocation can be managed and ensured, and then document it.

2022-05-09 09:37 UTC, bodo-sai commented on Kubernetes/README.md
> -### Step 1: Create a Kubernetes Cluster in EKS
Yes, we can it as an Optional one at the end maybe.

2022-05-09 09:38 UTC, bodo-sai commented on Kubernetes/README.md
> +You can use this as the base image for your own docker image. For testing and validation purposes this image also includes the [Chicago Crimes example](docker/chicago_crimes.py), which is used in thi
But @alifarhid pointed out that pi.py is not a good explanation of what bodo is capable of

2022-05-09 09:41 UTC, bodo-sai commented on Kubernetes/docker/Dockerfile
> +ENV PATH /root/miniconda3/bin/:${PATH}
We are not using root for execution, we are just installing using root user and providing access to root folder for mpi user

2022-05-09 09:42 UTC, bodo-sai commented on Kubernetes/mpijob.yaml
> +apiVersion: kubeflow.org/v1
It's a mistake from my end

2022-05-10 19:51 UTC, alifarhid approved these changes

2022-05-10 19:51 UTC, merged

2022-05-11 13:58 UTC, sahil1105 commented on Kubernetes/docker/Dockerfile
> +RUN conda install -y mamba -c conda-forge && mamba install -y bodo -c bodo.ai -c conda-forge
I would fix the bodo version for reproducibility purposes. Or add a note that this was tested with so and so version.

2022-05-11 14:58 UTC, alifarhid commented on Kubernetes/README.md
> +You can use this as the base image for your own docker image. For testing and validation purposes this image also includes the [pi calculation example](docker/chicago_crimes.py), which is used in thi
If it is supposed to be pi calculation, please also fix the docker/chicago_crimes.py to docker/pi.py. Not sure. @bodo-sai please check.

2022-05-11 14:59 UTC, alifarhid commented on Kubernetes/docker/Dockerfile
> +RUN conda install -y mamba -c conda-forge && mamba install -y bodo -c bodo.ai -c conda-forge
@bodo-sai please check. I already saw you used mamba in the new docker file. Not sure why it's back to older one.

2022-05-11 15:16 UTC, bodo-sai commented on Kubernetes/README.md
> +You can use this as the base image for your own docker image. For testing and validation purposes this image also includes the [pi calculation example](docker/chicago_crimes.py), which is used in thi
It's a type